=== rpane/FrontEnd/HTML XML CSS/Random/XML/bookstoreschema.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="bookstore">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="price" type="xs:float"/>
              <xs:element name="comments" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="userComment" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="rating">
                              <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                  <xs:minInclusive value="1"/>
                                  <xs:maxInclusive value="4"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ISBN" type="xs:double"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rpane/FrontEnd/HTML XML CSS/Random/XML/bookstoreschema.xml
<?xml version="1.0" ?>
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bookstoreschema.xsd">
  <book ISBN="12315464">
    <title>Starwars: The Last Jedi</title>
    <price>39.95</price>
    <comments>
      <userComment rating="1"></userComment>
    </comments>
  </book>
  <book ISBN="131846413132">
    <title>Indiana Jones</title>
    <price>34.95</price>
    <comments>
      <userComment rating="3"></userComment>
    </comments>
  </book>
  <book ISBN="213184561321">
    <title>Silence of the Lambs</title>
    <price>19.95</price>
    <comments>
      <userComment rating="4"></userComment>
    </comments>
  </book>
  <book ISBN="231654641231">
    <title>Lord of the Rings</title>
    <price>25.95</price>
    <comments>
      <userComment rating="4"></userComment>
    </comments>
  </book>
</bookstore>
